import type { KnowledgeEntity, KnowledgeLibrary, KnowledgeRelationship, EntityKind } from "./types";

const entities: KnowledgeEntity[] = [];
const relationships: KnowledgeRelationship[] = [];
const medline = (slug: string, title: string) => ({ title, organization: "MedlinePlus · National Library of Medicine", url: `https://medlineplus.gov/${slug}.${slug.startsWith("ency/") ? "htm" : "html"}` });

const systems = [
  ["cardiovascular", "Cardiovascular system", "The heart and blood vessels circulate blood, delivering oxygen and nutrients throughout the body."],
  ["respiratory", "Respiratory system", "The airways and lungs bring oxygen into the body and remove carbon dioxide."],
  ["digestive", "Digestive system", "The digestive tract, liver, pancreas, and gallbladder work together to process food and absorb nutrients."],
  ["nervous", "Nervous system", "The brain, spinal cord, and nerves coordinate sensation, movement, thinking, and many automatic functions."],
  ["musculoskeletal", "Musculoskeletal system", "Bones, muscles, joints, and connective tissues support the body and make movement possible."],
  ["endocrine", "Endocrine system", "Hormone-producing glands help regulate metabolism, growth, reproduction, and other body processes."],
  ["immune", "Immune system", "A network of cells, tissues, and organs helps defend against infection and other threats."],
  ["urinary", "Urinary system", "The kidneys filter blood and help balance fluids; the ureters, bladder, and urethra transport and store urine."],
  ["reproductive", "Reproductive system", "Reproductive organs and hormones support sexual development, fertility, and reproduction."],
  ["integumentary", "Integumentary system", "Skin, hair, and nails form a protective barrier and help regulate body temperature."],
];
for (const [id, name, description] of systems) entities.push({ id, name, description, kind: "body-system", bodySystem: id, details: { overview: description, category: "Human anatomy" }, sources: [medline("anatomy", "Anatomy and body systems")] });

const symptoms = [
  ["wheezing", "Wheezing", "A high-pitched whistling sound during breathing, often related to narrowed airways.", "respiratory"],
  ["cough", "Cough", "A protective reflex that clears the airways. It may occur for many different reasons.", "respiratory"],
  ["shortness-of-breath", "Shortness of breath", "A sensation of difficult or uncomfortable breathing. Sudden or severe breathing difficulty needs emergency attention.", "respiratory"],
  ["chest-tightness", "Chest tightness", "A feeling of pressure or constriction in the chest. New or severe chest symptoms need urgent assessment.", "respiratory"],
  ["headache", "Headache", "Pain or discomfort in the head or face. Headaches have many causes and patterns.", "nervous"],
  ["fatigue", "Fatigue", "Persistent tiredness or reduced energy that may have physical, psychological, or lifestyle-related contributors.", null],
  ["nausea", "Nausea", "A feeling of needing to vomit, which can occur with digestive conditions and many other causes.", "digestive"],
  ["dizziness", "Dizziness", "A broad term for feeling lightheaded, unsteady, or as if the surroundings are moving.", "nervous"],
  ["fever", "Fever", "An elevated body temperature, often part of the body's response to infection or inflammation.", "immune"],
  ["joint-pain", "Joint pain", "Discomfort affecting one or more joints, with many possible mechanical or inflammatory causes.", "musculoskeletal"],
  ["joint-stiffness", "Joint stiffness", "A feeling of restricted or difficult movement in a joint, sometimes worse after rest.", "musculoskeletal"],
  ["skin-rash", "Skin rash", "A change in the color, texture, or appearance of the skin, which can have many causes.", "integumentary"],
  ["itching", "Itching", "An uncomfortable skin sensation that creates an urge to scratch.", "integumentary"],
  ["sneezing", "Sneezing", "A reflex that expels air through the nose and mouth in response to irritation.", "respiratory"],
  ["runny-nose", "Runny nose", "Drainage of mucus from the nose, which can accompany allergies, infections, or irritation.", "respiratory"],
  ["heartburn", "Heartburn", "A burning sensation behind the breastbone, often associated with stomach contents moving into the esophagus.", "digestive"],
  ["abdominal-pain", "Abdominal pain", "Discomfort between the chest and pelvis. Location and severity alone cannot establish a cause.", "digestive"],
  ["bloating", "Bloating", "A sensation of fullness, pressure, or swelling in the abdomen.", "digestive"],
  ["diarrhea", "Diarrhea", "Loose or watery stools occurring more frequently than usual.", "digestive"],
  ["constipation", "Constipation", "Infrequent or difficult bowel movements, sometimes with hard stools.", "digestive"],
  ["increased-thirst", "Increased thirst", "Feeling a greater need to drink than usual; several health and environmental factors may contribute.", "endocrine"],
  ["frequent-urination", "Frequent urination", "Passing urine more often than usual. This can occur for many reasons.", "urinary"],
  ["blurred-vision", "Blurred vision", "Reduced sharpness of vision. Sudden changes in vision warrant prompt professional assessment.", "nervous"],
  ["tingling", "Tingling", "A pins-and-needles sensation that can occur with temporary pressure on nerves or other conditions.", "nervous"],
  ["low-mood", "Low mood", "Feeling persistently sad, empty, or down. Duration and effects on daily life are important in assessment.", "nervous"],
  ["loss-of-interest", "Loss of interest", "Reduced enjoyment of or interest in activities that were previously rewarding.", "nervous"],
  ["worry", "Excessive worry", "Persistent apprehension that can be difficult to control and may interfere with everyday life.", "nervous"],
  ["sleep-difficulties", "Sleep difficulties", "Difficulty falling asleep, staying asleep, or getting restorative sleep.", "nervous"],
  ["cold-intolerance", "Cold intolerance", "Unusual sensitivity to cold temperatures compared with other people.", "endocrine"],
  ["weight-gain", "Weight gain", "An increase in body weight, which can reflect a variety of interacting factors.", "endocrine"],
  ["painful-urination", "Painful urination", "Pain, burning, or discomfort when passing urine, which requires assessment if persistent.", "urinary"],
  ["back-pain", "Back pain", "Discomfort in the back that may arise from muscles, joints, nerves, or other structures.", "musculoskeletal"],
  ["pelvic-pain", "Pelvic pain", "Pain in the lower abdomen or pelvis; it can have reproductive, urinary, digestive, or other causes.", "reproductive"],
  ["heavy-periods", "Heavy menstrual bleeding", "Menstrual bleeding that is heavier or lasts longer than usual and may affect quality of life.", "reproductive"],
  ["chest-pain", "Chest pain", "Pain or discomfort in the chest. New, severe, or persistent chest pain requires immediate medical attention.", "cardiovascular"],
  ["palpitations", "Palpitations", "The sensation of a fast, pounding, fluttering, or irregular heartbeat.", "cardiovascular"],
  ["light-sensitivity", "Light sensitivity", "Discomfort or pain with light exposure, which can accompany several eye or neurological conditions.", "nervous"],
  ["swelling", "Swelling", "Enlargement of a body area due to fluid buildup or inflammation.", null],
] as const;
for (const [id, name, description, bodySystem] of symptoms) entities.push({ id, name, description, bodySystem, kind: "symptom", details: { overview: description, safety: "A symptom can have many possible causes. This information is educational and does not provide a diagnosis.", attention: ["shortness-of-breath", "chest-pain", "chest-tightness"].includes(id) ? "Sudden or severe breathing difficulty, new or severe chest pain, fainting, or blue lips may be an emergency. Contact your local emergency service immediately." : id === "headache" ? "A sudden, extremely severe headache, or headache with weakness, confusion, fever and stiff neck, or after a head injury needs immediate medical assessment." : "Seek professional advice for new, persistent, worsening, or concerning symptoms. Sudden severe symptoms may need emergency care." }, sources: [] });

const treatments: [string, string, string, string, string][] = [
  ["asthma-action-plan", "Asthma action plan", "Care planning", "A written plan developed with a clinician describes routine asthma care and what to do when symptoms change.", "A plan is individualized by a healthcare professional and is not a substitute for emergency care."],
  ["inhaler-therapy", "Inhaled medicines", "Respiratory care", "Inhalers deliver medicines to the airways. Different inhalers have different roles in ongoing control and symptom relief.", "Correct device technique and the clinician's instructions matter. Not every inhaler is intended for sudden symptoms."],
  ["trigger-management", "Trigger management", "Environmental care", "Identifying and limiting relevant exposures can be one part of a broader management plan.", "Triggers differ between people. Avoid unnecessary restrictions and discuss concerns with a clinician."],
  ["physical-therapy", "Physical therapy", "Rehabilitation", "Guided movement, exercises, and functional training can support mobility and daily activities.", "Programs should take individual abilities and medical conditions into account."],
  ["nutritional-therapy", "Nutrition support", "Lifestyle support", "A balanced eating pattern and, when needed, dietitian-guided changes can support management of some health conditions.", "Nutritional needs vary. Restrictive diets or supplements may be inappropriate without professional guidance."],
  ["physical-activity", "Physical activity", "Lifestyle support", "Appropriate physical activity can support cardiovascular, metabolic, musculoskeletal, and mental health.", "Activity plans may need to be adapted for symptoms, disabilities, pregnancy, or existing conditions."],
  ["smoking-cessation", "Smoking cessation support", "Preventive care", "Counseling and, where appropriate, medicines help people reduce tobacco-related health risks.", "A healthcare professional can help choose suitable cessation methods."],
  ["cognitive-behavioral-therapy", "Cognitive behavioral therapy", "Psychological therapy", "A structured talking therapy explores patterns in thoughts and behavior and builds coping skills.", "A trained professional adapts the approach. Crisis symptoms need immediate support."],
  ["psychotherapy", "Psychotherapy", "Psychological therapy", "Talking therapies can help people understand emotions, manage difficulties, and improve functioning.", "The form and duration of treatment depend on an assessment and shared decisions."],
  ["emollient-therapy", "Moisturizing skin care", "Skin care", "Emollients help support the skin barrier and reduce dryness in conditions such as eczema.", "Some products can irritate skin. Certain emollient residues on fabric are a fire hazard."],
  ["phototherapy", "Phototherapy", "Dermatological care", "Medically supervised ultraviolet light may help selected inflammatory skin conditions.", "Treatment requires professional supervision because excessive exposure can damage skin."],
  ["cpap", "Positive airway pressure", "Sleep medicine", "A device provides gentle air pressure to help keep the airway open during sleep in appropriate sleep apnea cases.", "Diagnosis, device selection, fitting, and follow-up are handled by a sleep-care team."],
  ["pulmonary-rehabilitation", "Pulmonary rehabilitation", "Rehabilitation", "A supervised program combines exercise, education, and support for people with some chronic lung conditions.", "The program is tailored by healthcare professionals and does not replace prescribed care."],
  ["sleep-habits", "Supportive sleep habits", "Lifestyle support", "Consistent sleep routines and a suitable sleep environment can support well-being alongside condition-specific care.", "Persistent sleep problems can require assessment; sleep habits alone do not treat sleep apnea."],
  ["iron-replacement", "Iron replacement", "Nutrient replacement", "Clinician-guided iron replacement may replenish depleted iron stores while the cause of deficiency is investigated.", "Excess iron is harmful, especially to children. Testing and professional guidance are important."],
  ["blood-pressure-management", "Blood pressure management", "Long-term care", "Regular assessment, lifestyle measures, and medicines when appropriate can reduce complications of high blood pressure.", "Targets and medicine choices depend on individual assessment. Do not change treatment without professional advice."],
  ["blood-glucose-management", "Blood glucose management", "Long-term care", "Education, monitoring, nutrition, activity, and medicines may be combined to manage diabetes.", "Care plans and glucose targets are individualized. Some medicines can cause low blood glucose."],
  ["pain-management", "Pain management", "Supportive care", "Management may combine physical, psychological, and medicine-based approaches appropriate to the underlying condition.", "Pain medicines have different risks. New or severe pain needs assessment rather than simply symptom suppression."],
  ["allergen-reduction", "Allergen exposure management", "Environmental care", "Limiting relevant allergen exposure may reduce symptoms for people with identified allergic triggers.", "The value of an avoidance measure depends on the specific allergy and exposure."],
  ["infection-management", "Infection management", "Infectious disease care", "Care depends on the organism and severity and may include supportive measures or targeted medicines.", "Antibiotics do not treat viral infections. Professional assessment guides their use."],
  ["surgical-care", "Surgical treatment", "Procedural care", "Procedures may be considered for selected conditions when their likely benefits outweigh the risks.", "Surgery requires specialist assessment, informed consent, and discussion of alternatives."],
  ["hormone-therapy", "Hormonal treatment", "Hormonal care", "Hormone-related medicines can alter hormone effects or replace deficient hormones for specific conditions.", "Suitability depends on the condition, medicine, health history, and reproductive goals."],
  ["hydration-support", "Hydration support", "Supportive care", "Maintaining appropriate fluid intake is relevant to general health and selected digestive or urinary conditions.", "Some heart or kidney conditions require fluid limits; needs are individual."],
  ["bone-health-care", "Bone health care", "Preventive and long-term care", "Fall prevention, appropriate exercise, nutrition, and sometimes medicines help reduce fracture risk.", "Supplement and medicine decisions depend on dietary intake, testing, and fracture risk assessment."],
  ["cardiac-rehabilitation", "Cardiac rehabilitation", "Rehabilitation", "A supervised program supports recovery and heart health through exercise, education, and risk-factor management.", "Participation follows professional assessment and is not suitable during an acute emergency."],
];
for (const [id, name, category, description, safety] of treatments) entities.push({ id, name, kind: "treatment", description, bodySystem: null, details: { category, overview: description, safety, mechanism: description }, sources: [] });

const medications: [string, string, string, string, string][] = [
  ["inhaled-corticosteroids", "Inhaled corticosteroids", "Anti-inflammatory medicines", "These medicines reduce airway inflammation and are used in asthma control and selected other respiratory conditions.", "They are not interchangeable with all reliever medicines. Local side effects can include oral thrush and voice changes."],
  ["bronchodilators", "Bronchodilators", "Airway-opening medicines", "These medicines relax muscles around the airways. Different classes have different durations and indications.", "Possible side effects depend on the drug and can include tremor or a fast heartbeat. Some are not for use alone in asthma."],
  ["antihistamines", "Antihistamines", "Allergy medicines", "These medicines block some effects of histamine and may reduce symptoms such as sneezing and itching.", "Some cause drowsiness or interact with other medicines. They do not replace emergency treatment for severe allergic reactions."],
  ["metformin", "Metformin", "Glucose-lowering medicine", "Metformin reduces glucose production by the liver and helps the body respond to insulin in type 2 diabetes.", "Kidney function and other health factors affect suitability. Digestive side effects can occur."],
  ["insulin", "Insulin", "Hormone replacement", "Insulin helps glucose enter cells and may be used in type 2 diabetes as well as other types of diabetes.", "Insulin can cause low blood glucose. Selection, dosing, and monitoring require individualized professional guidance."],
  ["antihypertensives", "Blood pressure medicines", "Antihypertensives", "Several medicine classes lower blood pressure through different effects on blood vessels, fluid balance, or heart function.", "Risks and monitoring differ by class. Some are unsuitable during pregnancy."],
  ["statins", "Statins", "Lipid-lowering medicines", "Statins reduce liver cholesterol production and can lower cardiovascular risk in people with appropriate indications.", "Suitability, interactions, and potential muscle or liver effects are discussed with a clinician."],
  ["triptans", "Triptans", "Migraine medicines", "Triptans act on serotonin receptors and may relieve migraine attacks in appropriate patients.", "They are not suitable for everyone, including some people with cardiovascular disease. Frequent use can worsen headache patterns."],
  ["topical-corticosteroids", "Topical corticosteroids", "Skin anti-inflammatory medicines", "These medicines reduce inflammation in selected skin conditions.", "Strength, location, and duration matter; inappropriate use can thin the skin or worsen some infections."],
  ["proton-pump-inhibitors", "Proton pump inhibitors", "Acid-suppressing medicines", "These medicines reduce stomach acid production and may help manage acid-related conditions.", "Persistent symptoms need assessment. A clinician should review the need for long-term treatment."],
  ["antidepressants", "Antidepressants", "Mental health medicines", "Several classes alter neurotransmitter signaling and may be used for depression, anxiety, or selected other conditions.", "Benefits can take time. Side effects, interactions, and changes in mood need monitoring. Do not stop abruptly without professional guidance."],
  ["levothyroxine", "Levothyroxine", "Thyroid hormone replacement", "Levothyroxine replaces thyroid hormone when the thyroid cannot produce enough.", "Blood tests guide individualized treatment. Other medicines and supplements can affect absorption."],
  ["antibiotics", "Antibiotics", "Antibacterial medicines", "Antibiotics treat certain bacterial infections by killing bacteria or preventing their growth.", "They do not treat viruses. Choice depends on the infection, allergies, resistance patterns, and other factors."],
  ["dmards", "Disease-modifying antirheumatic drugs", "Immunomodulating medicines", "DMARDs can reduce disease activity and help limit joint damage in conditions such as rheumatoid arthritis.", "These medicines require monitoring and can increase infection risk. Risks differ substantially between drugs."],
  ["bisphosphonates", "Bisphosphonates", "Bone-protective medicines", "These medicines slow bone breakdown and can reduce fracture risk in appropriately selected people.", "Kidney function, dental health, and other factors may affect suitability. Follow-up is important."],
];
for (const [id, name, category, description, safety] of medications) entities.push({ id, name, kind: "medication", description, bodySystem: null, details: { category, overview: description, safety, mechanism: description }, sources: [] });

const risks = [
  ["tobacco-smoke", "Tobacco smoke", "Tobacco smoke damages many tissues and can increase the risk or severity of several health conditions."],
  ["allergens", "Allergens", "Substances such as pollen, dust mites, or animal dander can trigger symptoms in people who are sensitized to them."],
  ["family-history", "Family history", "Inherited traits and shared environments may influence risk. A family history does not mean a condition will develop."],
  ["increasing-age", "Increasing age", "The frequency of some conditions changes with age, but age alone does not determine health."],
  ["air-pollution", "Air pollution", "Airborne pollutants can irritate the respiratory tract and contribute to cardiovascular and respiratory risks."],
  ["physical-inactivity", "Physical inactivity", "Low activity levels can contribute to several health risks alongside other individual and environmental factors."],
  ["excess-body-weight", "Excess body weight", "Body composition and weight can influence some conditions; they are only part of a complex health picture."],
  ["stress", "Stress", "Stress may influence symptoms or coping in some conditions. It is not a universal cause of illness."],
  ["infection", "Infections", "Viruses, bacteria, and other organisms can cause illness or trigger symptoms in some existing conditions."],
  ["dietary-factors", "Dietary factors", "Nutrient intake and eating patterns may contribute to selected health conditions; individual effects vary."],
  ["autoimmune-processes", "Autoimmune processes", "An immune response against the body's own tissues contributes to certain conditions."],
  ["low-iron-intake", "Low iron availability", "Low intake, reduced absorption, or blood loss can reduce the amount of iron available to the body."],
  ["hormonal-factors", "Hormonal factors", "Hormone levels and changes can influence some symptoms and health conditions."],
  ["occupational-exposures", "Occupational exposures", "Dusts, fumes, chemicals, or repetitive physical loads at work may contribute to particular health risks."],
];
for (const [id, name, description] of risks) entities.push({ id, name, kind: "risk-factor", description, bodySystem: null, details: { overview: description, safety: "An associated factor does not prove causation or predict whether an individual will develop a condition." }, sources: [] });

type ConditionInput = { id: string; name: string; system: string; source: string; description: string; context: string; symptoms: string[]; risks: string[]; causes: string[]; treatments: string[]; related?: string[]; diagnosis: string; attention?: string };
const conditions: ConditionInput[] = [
  { id: "asthma", name: "Asthma", system: "respiratory", source: "asthma", description: "A long-term condition in which the airways become inflamed and narrow, making breathing more difficult.", context: "Symptoms may come and go, and their frequency and severity vary. Asthma can affect people of any age; a care plan can help manage symptoms and reduce flare-ups.", symptoms: ["wheezing", "cough", "shortness-of-breath", "chest-tightness"], risks: ["allergens", "tobacco-smoke", "family-history", "air-pollution"], causes: ["An interaction of genetic and environmental factors", "Triggers may include allergens, respiratory infections, smoke, exercise, or cold air"], treatments: ["inhaler-therapy", "asthma-action-plan", "trigger-management", "inhaled-corticosteroids", "bronchodilators"], related: ["allergic-rhinitis", "eczema", "copd"], diagnosis: "Clinicians consider symptom patterns, medical history, and lung-function tests such as spirometry. Other explanations for breathing symptoms may need to be excluded.", attention: "Severe breathing difficulty, inability to speak in full sentences, blue lips, or reduced alertness requires immediate emergency care." },
  { id: "type-2-diabetes", name: "Type 2 diabetes", system: "endocrine", source: "diabetestype2", description: "A condition in which the body does not use insulin effectively and blood glucose levels become too high.", context: "It often develops gradually and may cause no noticeable symptoms for years. Ongoing management aims to support well-being and reduce long-term complications.", symptoms: ["increased-thirst", "frequent-urination", "fatigue", "blurred-vision", "tingling"], risks: ["family-history", "physical-inactivity", "excess-body-weight", "increasing-age"], causes: ["Insulin resistance combined with insufficient insulin production", "A combination of genetic, metabolic, and environmental influences"], treatments: ["blood-glucose-management", "nutritional-therapy", "physical-activity", "metformin", "insulin"], related: ["hypertension", "coronary-artery-disease"], diagnosis: "Blood tests such as A1C, fasting plasma glucose, or an oral glucose tolerance test are used. Confirmatory testing is often needed.", attention: "Confusion, fainting, severe dehydration, or difficulty breathing can indicate a medical emergency. New persistent thirst or urination changes deserve professional assessment." },
  { id: "hypertension", name: "Hypertension", system: "cardiovascular", source: "highbloodpressure", description: "Persistently elevated pressure in the arteries, often without noticeable symptoms.", context: "Over time, untreated high blood pressure can affect the heart, brain, kidneys, and blood vessels. Regular measurement is important because symptoms are not a reliable guide.", symptoms: [], risks: ["family-history", "increasing-age", "dietary-factors", "physical-inactivity", "excess-body-weight"], causes: ["Often develops from multiple genetic and environmental influences", "Sometimes linked to kidney disease, hormonal conditions, or medicines"], treatments: ["blood-pressure-management", "nutritional-therapy", "physical-activity", "antihypertensives", "smoking-cessation"], related: ["coronary-artery-disease", "type-2-diabetes", "sleep-apnea"], diagnosis: "Repeated, correctly performed blood pressure measurements are usually needed. Home or ambulatory monitoring may help confirm the pattern.", attention: "Very high readings accompanied by chest pain, severe headache, breathing difficulty, weakness, or vision changes need emergency assessment." },
  { id: "migraine", name: "Migraine", system: "nervous", source: "migraine", description: "A neurological condition that can cause recurring headache attacks and other sensory symptoms.", context: "Attacks may involve throbbing pain, nausea, and sensitivity to light or sound. Some people experience aura, and not every attack has the same features.", symptoms: ["headache", "nausea", "light-sensitivity", "dizziness", "fatigue"], risks: ["family-history", "stress", "hormonal-factors"], causes: ["Complex changes in brain signaling; exact mechanisms are still being studied", "Triggers vary and may include sleep disruption or hormonal changes"], treatments: ["pain-management", "triptans", "trigger-management", "sleep-habits"], diagnosis: "Diagnosis generally relies on the pattern of attacks and clinical examination. Tests may be used if symptoms suggest another cause.", attention: "A sudden worst-ever headache, new weakness, confusion, fever with a stiff neck, or a new headache after injury needs urgent assessment." },
  { id: "osteoarthritis", name: "Osteoarthritis", system: "musculoskeletal", source: "osteoarthritis", description: "A joint condition involving changes in cartilage, bone, and other joint tissues.", context: "It can cause pain and stiffness, commonly in the hands, knees, hips, or spine. Symptoms and imaging findings do not always match.", symptoms: ["joint-pain", "joint-stiffness", "swelling"], risks: ["increasing-age", "excess-body-weight", "family-history", "occupational-exposures"], causes: ["Changes in the whole joint over time", "Previous joint injury and mechanical loading may contribute"], treatments: ["physical-therapy", "physical-activity", "pain-management", "surgical-care"], related: ["rheumatoid-arthritis"], diagnosis: "Assessment includes symptoms and examination. X-rays may help, while blood tests can help assess alternative causes of joint symptoms." },
  { id: "allergic-rhinitis", name: "Allergic rhinitis", system: "immune", source: "hayfever", description: "Inflammation inside the nose caused by an allergic response to substances in the environment.", context: "Often called hay fever, it may occur seasonally or throughout the year. Symptoms can affect sleep and daily activities.", symptoms: ["sneezing", "runny-nose", "itching", "cough"], risks: ["allergens", "family-history"], causes: ["An immune response to allergens such as pollen, dust mites, or animal dander"], treatments: ["allergen-reduction", "antihistamines", "trigger-management"], related: ["asthma", "eczema"], diagnosis: "History and examination are central; selected skin or blood allergy tests can help identify relevant allergens." },
  { id: "eczema", name: "Eczema", system: "integumentary", source: "eczema", description: "A group of inflammatory skin conditions that can cause dryness, itching, and a recurring rash.", context: "Atopic dermatitis is a common form. Skin-barrier and immune differences contribute, and eczema is not contagious.", symptoms: ["itching", "skin-rash", "sleep-difficulties"], risks: ["family-history", "allergens", "stress"], causes: ["Interactions between the skin barrier, immune system, genes, and environment", "Irritants and some exposures may worsen symptoms"], treatments: ["emollient-therapy", "topical-corticosteroids", "trigger-management", "phototherapy"], related: ["asthma", "allergic-rhinitis", "psoriasis"], diagnosis: "Diagnosis is usually based on skin examination and history. Testing may be considered to rule out infection or contact allergy." },
  { id: "gerd", name: "Gastroesophageal reflux disease", system: "digestive", source: "gerd", description: "A condition in which stomach contents repeatedly flow back into the esophagus and cause troublesome symptoms or complications.", context: "Heartburn is common, but not everyone has it. Persistent reflux should be assessed because several conditions can cause similar symptoms.", symptoms: ["heartburn", "cough", "nausea", "chest-pain"], risks: ["excess-body-weight", "tobacco-smoke", "dietary-factors"], causes: ["Impaired function of the barrier between the stomach and esophagus", "A hiatal hernia may contribute in some cases"], treatments: ["nutritional-therapy", "proton-pump-inhibitors", "smoking-cessation", "surgical-care"], diagnosis: "History may be sufficient initially. Endoscopy or reflux monitoring may be used for selected persistent symptoms or warning features.", attention: "New or severe chest pain requires urgent assessment rather than assuming reflux. Trouble swallowing, vomiting blood, or unintentional weight loss needs prompt care." },
  { id: "depression", name: "Depression", system: "nervous", source: "depression", description: "A mental health condition that can affect mood, interest, thinking, sleep, and daily functioning.", context: "Depression is more than a brief period of sadness. Presentations vary, and effective support can include psychological therapies, medicines, and social approaches.", symptoms: ["low-mood", "loss-of-interest", "fatigue", "sleep-difficulties"], risks: ["family-history", "stress", "hormonal-factors"], causes: ["A complex interaction of biological, psychological, and social factors"], treatments: ["psychotherapy", "cognitive-behavioral-therapy", "antidepressants", "physical-activity", "sleep-habits"], related: ["anxiety-disorders"], diagnosis: "A healthcare professional evaluates symptoms, duration, functioning, safety, medical history, and possible alternative causes.", attention: "If there is immediate danger or thoughts of acting on self-harm, contact local emergency services or a crisis service immediately. In the US, call or text 988." },
  { id: "anxiety-disorders", name: "Anxiety disorders", system: "nervous", source: "anxiety", description: "A group of conditions involving excessive fear or worry that can interfere with everyday activities.", context: "Different anxiety disorders have different patterns. Physical symptoms can occur, but a professional assessment is needed to understand their cause.", symptoms: ["worry", "palpitations", "sleep-difficulties", "fatigue", "nausea"], risks: ["family-history", "stress"], causes: ["Interactions among temperament, biology, life experiences, and environment"], treatments: ["cognitive-behavioral-therapy", "psychotherapy", "antidepressants", "physical-activity", "sleep-habits"], related: ["depression", "irritable-bowel-syndrome"], diagnosis: "Assessment explores symptom patterns, duration, impact, and physical or substance-related explanations." },
  { id: "copd", name: "COPD", system: "respiratory", source: "copd", description: "Chronic obstructive pulmonary disease causes persistent airflow limitation and breathing difficulties.", context: "COPD includes emphysema and chronic bronchitis. Progression and symptom burden vary, and management can improve functioning and reduce exacerbations.", symptoms: ["shortness-of-breath", "cough", "wheezing", "fatigue"], risks: ["tobacco-smoke", "air-pollution", "occupational-exposures", "family-history"], causes: ["Long-term exposure to lung irritants", "Rare inherited conditions, including alpha-1 antitrypsin deficiency"], treatments: ["smoking-cessation", "bronchodilators", "inhaler-therapy", "pulmonary-rehabilitation", "inhaled-corticosteroids"], related: ["asthma", "pneumonia"], diagnosis: "Spirometry, interpreted alongside symptoms and exposure history, is central to diagnosis.", attention: "A marked increase in breathlessness, blue lips, confusion, or difficulty speaking needs immediate medical help." },
  { id: "coronary-artery-disease", name: "Coronary artery disease", system: "cardiovascular", source: "coronaryarterydisease", description: "A condition in which the heart's arteries become narrowed or otherwise unable to supply enough blood.", context: "Plaque buildup is a common cause. Some people have no symptoms until a complication occurs; others experience angina or reduced exercise tolerance.", symptoms: ["chest-pain", "shortness-of-breath", "fatigue"], risks: ["tobacco-smoke", "family-history", "increasing-age", "physical-inactivity", "dietary-factors"], causes: ["Atherosclerotic plaque buildup in coronary arteries", "Other coronary blood-vessel abnormalities can also affect blood flow"], treatments: ["statins", "blood-pressure-management", "smoking-cessation", "cardiac-rehabilitation", "surgical-care"], related: ["hypertension", "type-2-diabetes"], diagnosis: "Clinical assessment may include blood tests, electrocardiography, stress testing, and selected coronary imaging.", attention: "New chest pressure or pain, especially with sweating, nausea, or breathlessness, can be an emergency. Contact emergency services immediately." },
  { id: "hypothyroidism", name: "Hypothyroidism", system: "endocrine", source: "hypothyroidism", description: "A condition in which the thyroid does not produce enough thyroid hormone.", context: "Symptoms can develop gradually and overlap with many other conditions. Thyroid hormone affects numerous body functions.", symptoms: ["fatigue", "cold-intolerance", "weight-gain", "constipation", "low-mood"], risks: ["autoimmune-processes", "family-history", "increasing-age"], causes: ["Autoimmune thyroid damage is a common cause", "Thyroid surgery, radiation, or some medicines may contribute"], treatments: ["levothyroxine", "hormone-therapy"], diagnosis: "Blood levels of thyroid-stimulating hormone and free thyroxine are commonly used, interpreted in clinical context." },
  { id: "iron-deficiency-anemia", name: "Iron deficiency anemia", system: "cardiovascular", source: "ency/article/000584", description: "Reduced healthy red blood cells due to insufficient iron for normal hemoglobin production.", context: "Iron deficiency may result from blood loss, low intake, increased needs, or poor absorption. Identifying its cause is important.", symptoms: ["fatigue", "dizziness", "shortness-of-breath", "palpitations", "headache"], risks: ["low-iron-intake", "dietary-factors"], causes: ["Blood loss, including heavy menstrual bleeding or digestive bleeding", "Insufficient iron intake, impaired absorption, or increased requirements"], treatments: ["iron-replacement", "nutritional-therapy"], related: ["endometriosis"], diagnosis: "A complete blood count and iron studies, including ferritin, help assess anemia and iron status. Additional evaluation looks for the underlying cause." },
  { id: "osteoporosis", name: "Osteoporosis", system: "musculoskeletal", source: "osteoporosis", description: "Reduced bone strength that increases the likelihood of fractures.", context: "It commonly has no symptoms until a fracture occurs. Prevention and care focus on fracture risk, bone health, and falls.", symptoms: ["back-pain"], risks: ["increasing-age", "family-history", "hormonal-factors", "tobacco-smoke", "physical-inactivity"], causes: ["An imbalance between bone breakdown and formation", "Hormone changes, some medicines, and other conditions may contribute"], treatments: ["bone-health-care", "physical-activity", "nutritional-therapy", "bisphosphonates"], diagnosis: "Bone density testing and clinical fracture-risk assessment guide diagnosis and management. Back pain can occur with vertebral fractures, not necessarily with osteoporosis itself." },
  { id: "influenza", name: "Influenza", system: "respiratory", source: "flu", description: "A contagious respiratory illness caused by influenza viruses.", context: "Illness can range from mild to severe. Older adults, young children, pregnant people, and people with some chronic conditions have greater complication risks.", symptoms: ["fever", "cough", "headache", "fatigue", "runny-nose"], risks: ["infection", "increasing-age"], causes: ["Infection with influenza viruses spread mainly through respiratory particles"], treatments: ["infection-management", "hydration-support"], related: ["pneumonia", "asthma"], diagnosis: "Clinical assessment and, when useful, respiratory tests identify influenza. Other viruses can produce similar symptoms.", attention: "Breathing difficulty, chest pain, confusion, dehydration, or symptoms that improve then sharply worsen warrant urgent care." },
  { id: "urinary-tract-infection", name: "Urinary tract infection", system: "urinary", source: "urinarytractinfections", description: "An infection affecting part of the urinary tract, most commonly the bladder.", context: "Symptoms and severity depend on the location. Kidney infections can be more serious and need prompt treatment.", symptoms: ["painful-urination", "frequent-urination", "pelvic-pain", "fever", "back-pain"], risks: ["infection", "hormonal-factors"], causes: ["Usually bacteria entering and multiplying in the urinary tract"], treatments: ["antibiotics", "infection-management", "hydration-support"], related: ["kidney-stones"], diagnosis: "Symptoms, a urine test, and sometimes a urine culture guide assessment. Not all urinary symptoms are due to infection.", attention: "Fever with flank or back pain, vomiting, pregnancy with urinary symptoms, or feeling severely unwell needs prompt professional assessment." },
  { id: "irritable-bowel-syndrome", name: "Irritable bowel syndrome", system: "digestive", source: "irritablebowelsyndrome", description: "A disorder of gut-brain interaction involving recurrent abdominal pain and changes in bowel habits.", context: "IBS patterns differ and may include diarrhea, constipation, or both. It does not itself cause the bowel damage seen in inflammatory bowel disease.", symptoms: ["abdominal-pain", "bloating", "diarrhea", "constipation"], risks: ["stress", "infection", "family-history"], causes: ["Changes in gut-brain signaling, bowel sensitivity, and movement may contribute", "Some cases begin after a gastrointestinal infection"], treatments: ["nutritional-therapy", "cognitive-behavioral-therapy", "physical-activity", "hydration-support"], related: ["anxiety-disorders"], diagnosis: "A clinician considers the symptom pattern and checks for warning features. Tests may be used to rule out other conditions.", attention: "Blood in stools, unexplained weight loss, anemia, persistent fever, or new severe abdominal pain needs medical evaluation." },
  { id: "rheumatoid-arthritis", name: "Rheumatoid arthritis", system: "immune", source: "rheumatoidarthritis", description: "An autoimmune inflammatory condition that commonly affects joints and can involve other parts of the body.", context: "Persistent inflammation can damage joints. Early professional assessment and appropriate treatment can help protect function.", symptoms: ["joint-pain", "joint-stiffness", "swelling", "fatigue"], risks: ["autoimmune-processes", "family-history", "tobacco-smoke"], causes: ["An immune response directed against joint and other tissues", "Genetic and environmental influences interact"], treatments: ["dmards", "physical-therapy", "pain-management", "physical-activity"], related: ["osteoarthritis", "osteoporosis"], diagnosis: "Examination, symptom history, blood tests for inflammation and antibodies, and imaging may be combined. No single test establishes every case." },
  { id: "psoriasis", name: "Psoriasis", system: "integumentary", source: "psoriasis", description: "An immune-mediated condition that speeds up skin-cell turnover and can cause thickened, scaly patches.", context: "Appearance varies with skin tone and psoriasis type. It is not contagious; some people also develop inflammatory arthritis.", symptoms: ["skin-rash", "itching", "joint-pain"], risks: ["family-history", "autoimmune-processes", "stress", "tobacco-smoke"], causes: ["Immune signaling and genetic susceptibility", "Infections, skin injury, and other triggers may provoke flares"], treatments: ["topical-corticosteroids", "emollient-therapy", "phototherapy", "dmards"], related: ["eczema"], diagnosis: "Skin and nail examination is usually central. A biopsy is sometimes used when the diagnosis is uncertain." },
  { id: "kidney-stones", name: "Kidney stones", system: "urinary", source: "kidneystones", description: "Hard mineral deposits that form in the kidneys and may move into the urinary tract.", context: "Small stones may pass without symptoms, while others can cause severe pain or obstruct urine flow. Stone type influences prevention.", symptoms: ["back-pain", "abdominal-pain", "nausea", "painful-urination"], risks: ["family-history", "dietary-factors", "excess-body-weight"], causes: ["Urine conditions that allow minerals to crystallize", "Low urine volume and certain metabolic or dietary factors may contribute"], treatments: ["hydration-support", "pain-management", "surgical-care", "nutritional-therapy"], related: ["urinary-tract-infection"], diagnosis: "Urine and blood tests, imaging, and sometimes analysis of a passed stone guide assessment.", attention: "Severe flank pain with fever, chills, inability to pass urine, or persistent vomiting requires urgent care." },
  { id: "endometriosis", name: "Endometriosis", system: "reproductive", source: "endometriosis", description: "A condition in which tissue similar to the uterine lining grows outside the uterus.", context: "It may cause pain and fertility difficulties, although symptoms vary and some people have few symptoms. The amount of disease does not reliably predict pain severity.", symptoms: ["pelvic-pain", "heavy-periods", "abdominal-pain", "fatigue"], risks: ["family-history", "hormonal-factors"], causes: ["The exact cause is not fully understood", "Hormonal, immune, and genetic factors may contribute"], treatments: ["hormone-therapy", "pain-management", "surgical-care"], related: ["iron-deficiency-anemia"], diagnosis: "History, examination, and imaging inform assessment. Laparoscopy may be used in selected situations; pathways vary with clinical context." },
  { id: "pneumonia", name: "Pneumonia", system: "respiratory", source: "pneumonia", description: "An infection that inflames the air sacs in one or both lungs.", context: "Different bacteria, viruses, and other organisms can cause pneumonia. Severity depends on the organism, age, and underlying health.", symptoms: ["cough", "fever", "shortness-of-breath", "chest-pain", "fatigue"], risks: ["infection", "increasing-age", "tobacco-smoke"], causes: ["Bacterial, viral, or less commonly fungal infection", "Aspiration can also contribute in some cases"], treatments: ["infection-management", "antibiotics", "hydration-support"], related: ["influenza", "copd"], diagnosis: "Clinical examination, oxygen measurement, chest imaging, and selected laboratory tests may be used. Antibiotics are appropriate for bacterial, not purely viral, causes.", attention: "Severe breathlessness, blue lips, confusion, or chest pain requires urgent medical attention." },
  { id: "sleep-apnea", name: "Sleep apnea", system: "respiratory", source: "sleepapnea", description: "A sleep-related breathing disorder involving repeated pauses or reductions in breathing.", context: "Obstructive sleep apnea involves upper-airway blockage; central sleep apnea has a different mechanism. Assessment helps establish the type and severity.", symptoms: ["fatigue", "headache", "sleep-difficulties"], risks: ["excess-body-weight", "increasing-age", "family-history"], causes: ["Repeated collapse of the upper airway in obstructive sleep apnea", "Altered breathing control in central sleep apnea"], treatments: ["cpap", "sleep-habits", "surgical-care"], related: ["hypertension", "type-2-diabetes"], diagnosis: "A sleep assessment and an overnight sleep study, at home or in a laboratory as appropriate, are used to assess breathing during sleep." },
];

for (const c of conditions) entities.push({ id: c.id, name: c.name, kind: "condition", description: c.description, bodySystem: c.system, details: { overview: `${c.description} ${c.context}`, diagnosis: c.diagnosis, causes: c.causes, attention: c.attention || "Discuss new, persistent, or worsening symptoms with a qualified healthcare professional. Sudden severe symptoms or feeling acutely unwell may require urgent or emergency care." }, sources: [medline(c.source, c.name)] });

function connect(sourceId: string, targetId: string, relationship: string, sourceReference: string) {
  const id = `${sourceId}--${targetId}`;
  if (!relationships.some(r => r.id === id || (relationship === "related topic" && r.sourceId === targetId && r.targetId === sourceId))) relationships.push({ id, sourceId, targetId, relationship, sourceReference });
}
for (const c of conditions) {
  const source = medline(c.source, c.name).url;
  connect(c.id, c.system, "involves body system", source);
  c.symptoms.forEach(id => connect(c.id, id, "may involve", source));
  c.risks.forEach(id => connect(c.id, id, "associated factor", source));
  c.treatments.forEach(id => connect(c.id, id, "management may include", source));
  c.related?.forEach(id => connect(c.id, id, "related topic", source));
}
for (const entity of entities) {
  if (entity.kind === "symptom" && entity.bodySystem) connect(entity.id, entity.bodySystem, "relevant body system", "https://medlineplus.gov/anatomy.html");
  if (!entity.sources.length) {
    const connectedIds = relationships.filter(r => r.targetId === entity.id && r.sourceId !== entity.id).map(r => r.sourceId);
    const sourceEntities = entities.filter(e => connectedIds.includes(e.id) && e.kind === "condition");
    entity.sources = sourceEntities.flatMap(e => e.sources).filter((s, i, all) => all.findIndex(v => v.url === s.url) === i).slice(0, 5);
    if (!entity.sources.length) entity.sources = [medline("healthtopics", "Health topics")];
  }
}
connect("inhaler-therapy", "inhaled-corticosteroids", "may deliver", "https://medlineplus.gov/asthma.html");
connect("inhaler-therapy", "bronchodilators", "may deliver", "https://medlineplus.gov/asthma.html");
connect("blood-glucose-management", "metformin", "may include", "https://medlineplus.gov/diabetestype2.html");
connect("blood-glucose-management", "insulin", "may include", "https://medlineplus.gov/diabetestype2.html");

export const seedLibrary: KnowledgeLibrary = { entities, relationships };
export const popularIds = ["asthma", "type-2-diabetes", "hypertension", "migraine"];
export const countKind = (kind: EntityKind) => entities.filter(e => e.kind === kind).length;
