"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, Check, ExternalLink, GitBranch, HeartHandshake, Network, Plus, Search, ShieldCheck } from "lucide-react";
import { useExplorer } from "./explorer-context";
import { BrandMark } from "./icons";
import { EmptyState, PageHeading, SafetyNote, SourceReferences } from "./ui";
import { DISCLAIMER } from "@/lib/types";

const organizations = [
  { name: "MedlinePlus", short: "MedlinePlus", organization: "National Library of Medicine", description: "Accessible health information about conditions, symptoms, medicines, and healthy living.", url: "https://medlineplus.gov/", tone: "teal" },
  { name: "National Institutes of Health", short: "NIH", organization: "U.S. Department of Health & Human Services", description: "Health and research resources from the nation's medical research agency and its institutes.", url: "https://www.nih.gov/health-information", tone: "blue" },
  { name: "Centers for Disease Control and Prevention", short: "CDC", organization: "U.S. public health agency", description: "Public health information about prevention, infectious diseases, and population health.", url: "https://www.cdc.gov/", tone: "blue" },
  { name: "World Health Organization", short: "WHO", organization: "United Nations specialized agency", description: "Global health information, fact sheets, and guidance on a broad range of health topics.", url: "https://www.who.int/health-topics", tone: "purple" },
];
export function SourcesPage() {
  const { library } = useExplorer();
  const [query, setQuery] = useState("");
  const sources = useMemo(() => library.entities.flatMap(e => e.sources).filter((source, i, all) => all.findIndex(s => s.url === source.url) === i).sort((a, b) => a.title.localeCompare(b.title)), [library]);
  const filtered = sources.filter(s => `${s.title} ${s.organization}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="sources-page page-enter"><PageHeading eyebrow="SOURCES & REFERENCES" title="Good knowledge begins with good sources." description="Explore the authoritative organizations behind our references, and follow the evidence back to its source."/>
    <div className="source-policy"><span><ShieldCheck size={28}/></span><div><h2>Transparent by design.</h2><p>Our educational summaries link to original health information so you can keep learning. This sample library is not exhaustive or independently clinically reviewed. Source organizations do not endorse this platform.</p></div></div>
    <div className="organization-grid">{organizations.map(org => <a className="organization-card" href={org.url} target="_blank" rel="noreferrer" key={org.name}><div className="organization-top"><span className={`organization-mark icon-${org.tone}`}>{org.short}</span><ExternalLink size={16}/></div><h2>{org.name}</h2><small>{org.organization}</small><p>{org.description}</p><span className="text-link">Visit the official website <ArrowUpRight size={15}/></span></a>)}</div>
    <div className="section-heading references-heading"><div><h2>References in the knowledge library</h2><p>{sources.length} distinct references, linked directly from our topic profiles.</p></div><div className="filter-search"><Search size={17}/><input aria-label="Search source references" placeholder="Find a topic reference..." value={query} onChange={e => setQuery(e.target.value)}/></div></div>{filtered.length ? <SourceReferences sources={filtered}/> : <EmptyState title="No references found" description="Try searching for a condition such as asthma or diabetes."/>}
    <div className="reference-principles"><div><BookOpen size={23}/><h3>Read in context</h3><p>A short summary cannot capture every detail. Original references provide more complete context.</p></div><div><GitBranch size={23}/><h3>Association is not causation</h3><p>Graph connections show educational relationships, not personal risk estimates or proof of a cause.</p></div><div><HeartHandshake size={23}/><h3>Care is personal</h3><p>A healthcare professional can apply evidence to an individual's circumstances and needs.</p></div></div>
  </div>;
}
export function AboutPage() {
  const { library } = useExplorer();
  return <div className="about-page page-enter"><PageHeading eyebrow="ABOUT HEALTH ATLAS" title="A clearer picture starts with a connection." description="Health Atlas makes health knowledge easier to explore—not by giving you answers about your body, but by helping you ask better questions."/>
    <section className="about-hero"><div><span className="hero-eyebrow">KNOWLEDGE FOR THE CURIOUS</span><h2>Less information overload.<br/>More understanding.</h2><p>Health topics don't exist in isolation. A symptom relates to many conditions; a treatment can have more than one role. This explorer makes those connections visible, so you can build a more informed perspective.</p><Link href="/explore" className="button button-primary">Start a discovery <ArrowRight size={17}/></Link></div><div className="about-brand-art"><span/><span/><span/><BrandMark/><Network size={140} strokeWidth={.6}/></div></section>
    <div className="about-numbers"><div><strong>{library.entities.length}</strong><span>educational topics</span></div><div><strong>{library.relationships.length}</strong><span>cited connections</span></div><div><strong>10</strong><span>body systems</span></div><div><strong>One</strong><span>connected perspective</span></div></div>
    <section className="about-steps" id="using-the-explorer"><div className="section-heading"><div><h2>Let your curiosity lead the way.</h2><p>A simple path from a question to a bigger picture.</p></div></div><div className="steps-grid">{[{ n: "01", title: "Find a starting point", text: "Search for a condition, symptom, treatment, medication, risk factor, or body system.", icon: Search }, { n: "02", title: "Follow a connection", text: "Open the graph, drag or select a node, and expand the relationships around it.", icon: Network }, { n: "03", title: "Look a little closer", text: "Read an educational profile, explore the sources, or compare two conditions.", icon: BookOpen }, { n: "04", title: "Keep your discoveries", text: "Bookmark topics to revisit. Your collection is saved privately for this browser.", icon: HeartHandshake }].map(step => <div className="step-card" key={step.n}><div><step.icon size={23}/><span>{step.n}</span></div><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>
    <section className="about-safety"><span><ShieldCheck size={32}/></span><div><span className="eyebrow">AN IMPORTANT DISTINCTION</span><h2>Built for education. Never for diagnosis.</h2><p>{DISCLAIMER}</p><div className="safety-promises"><span><Check size={16}/>No disease predictions</span><span><Check size={16}/>No personalized prescriptions</span><span><Check size={16}/>No dosage recommendations</span><span><Check size={16}/>No replacement for professional care</span></div></div></section>
    <section className="faq-section"><h2>A few things worth knowing.</h2>{[
      ["How are the connections created?", "The sample knowledge library uses structured relationships drawn from referenced health-information pages. Labels distinguish symptoms, associated factors, body systems, and management approaches. A relationship does not express likelihood, a personal recommendation, or proof of causation."],
      ["Is this a symptom checker?", "No. Selecting symptoms only opens educational information. The explorer does not evaluate a person's symptoms, predict a diagnosis, or rank possible diseases. Associated conditions are learning links, not suggestions about your health."],
      ["How is the information reviewed?", "This is a curated starter library based primarily on MedlinePlus educational references. It has not undergone independent clinical review and is not a complete medical encyclopedia. Always check the linked original sources, which may be updated independently, and consult a qualified healthcare professional for care decisions."],
      ["What happens when I save a topic?", "A random browser identifier is stored in a first-party, HTTP-only cookie. Bookmarks are saved to our database against that identifier. No name, email, or medical history is requested. Removing a bookmark deletes it from the collection. Clearing the cookie removes this browser's access to that collection; it does not automatically delete database records. There is no cross-device account."],
      ["What should I do in a medical emergency?", "Do not use this explorer to assess an emergency. Severe breathing difficulty, new or severe chest pain, sudden weakness or confusion, or other potentially life-threatening symptoms need immediate professional help. Contact your local emergency services. For a mental health crisis in the United States, call or text 988; if there is immediate danger, call emergency services."],
    ].map(([question, answer]) => <details key={question}><summary>{question}<Plus size={19}/></summary><p>{answer}</p></details>)}</section><SafetyNote urgent>If you think you may be experiencing a medical emergency, contact your local emergency services immediately. This platform cannot assess urgent symptoms.</SafetyNote>
  </div>;
}
