"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, GitBranch, Network, ShieldCheck, Stethoscope } from "lucide-react";
import { useExplorer } from "./explorer-context";
import { connectionsFor, connectionCount, kindLabels, type EntityKind, type KnowledgeEntity } from "@/lib/types";
import { EntityIcon } from "./icons";
import { KindBadge, SaveButton, SafetyNote, SourceReferences } from "./ui";

function TopicLinks({ entities }: { entities: KnowledgeEntity[] }) {
  return <div className="detail-topic-links">{entities.map(e => <Link href={`/topics/${e.id}`} key={e.id}><span className={`mini-topic-icon tone-${e.kind}`}><EntityIcon id={e.id} kind={e.kind} size={17}/></span><span>{e.name}</span><ArrowUpRight size={14}/></Link>)}</div>;
}
export function TopicView({ id }: { id: string }) {
  const { library } = useExplorer();
  const entity = library.entities.find(e => e.id === id)!;
  const related = connectionsFor(library, id);
  const ofKind = (kind: EntityKind) => related.filter(e => e.kind === kind);
  const conditions = ofKind("condition");
  const symptomIds = new Set(conditions.flatMap(c => connectionsFor(library, c.id, "symptom").map(e => e.id)).filter(v => v !== id));
  const riskIds = new Set(conditions.flatMap(c => connectionsFor(library, c.id, "risk-factor").map(e => e.id)));
  const system = library.entities.find(e => e.id === entity.bodySystem);
  const treatment = entity.kind === "treatment" || entity.kind === "medication";
  const backHref = entity.kind === "condition" ? "/conditions" : entity.kind === "symptom" ? "/symptoms" : treatment ? "/treatments" : entity.kind === "body-system" ? "/body-systems" : "/search";
  return <article className="topic-detail page-enter"><Link href={backHref} className="back-link"><ArrowLeft size={15}/>Back to {entity.kind === "body-system" ? "body systems" : treatment ? "treatments" : `${kindLabels[entity.kind].toLowerCase()}s`}</Link>
    <header className="detail-header"><div><KindBadge kind={entity.kind}/><h1>{entity.name}</h1><div className="detail-meta">{system && <Link href={`/topics/${system.id}`}><EntityIcon id={system.id} kind="body-system" size={16}/>{system.name}</Link>}<span><GitBranch size={15}/>{connectionCount(library, id)} connections</span><span><BookOpen size={15}/>Educational overview</span></div></div><div className="detail-header-actions"><SaveButton id={id} labeled/><Link href={`/explore?topic=${id}`} className="button button-primary"><Network size={17}/>Explore connections<ArrowUpRight size={16}/></Link></div></header>
    {entity.kind === "symptom" && <SafetyNote>A symptom can have many possible causes. This information is educational and does not provide a diagnosis. Associated conditions are not a ranked list of likely diagnoses.</SafetyNote>}
    {treatment && <SafetyNote>Treatment decisions should be made with a qualified healthcare professional. Do not start, stop, or change a medicine based on this educational overview.</SafetyNote>}
    <div className="detail-layout"><div className="detail-main"><section className="detail-section" id="overview"><span className="detail-section-label">THE BIG PICTURE</span><h2>What is {entity.name.toLowerCase()}?</h2><p>{entity.details.overview || entity.description}</p>{entity.details.category && <div className="detail-category"><strong>Category</strong><span>{entity.details.category}</span></div>}</section>
      {entity.kind === "condition" && <><section className="detail-section" id="symptoms"><h2>Common symptoms</h2><p>Symptoms can vary between people and overlap with many other conditions.</p>{ofKind("symptom").length ? <TopicLinks entities={ofKind("symptom")}/> : <SafetyNote compact>Hypertension often has no noticeable symptoms. Blood pressure measurements, not symptom matching, are needed to assess it.</SafetyNote>}</section><section className="detail-section" id="causes"><h2>Possible causes and triggers</h2><ul className="detail-bullets">{entity.details.causes?.map(cause => <li key={cause}>{cause}</li>)}</ul></section><section className="detail-section" id="risk-factors"><h2>Risk factors and associated influences</h2><p>A risk factor is not a prediction. These connections may represent susceptibility, triggers, or influences on symptoms.</p><TopicLinks entities={ofKind("risk-factor")}/></section><section className="detail-section" id="diagnosis"><h2>How clinicians assess it</h2><p>{entity.details.diagnosis}</p><div className="assessment-note"><Stethoscope size={19}/><span>Only a qualified healthcare professional can assess symptoms and make a diagnosis.</span></div></section><section className="detail-section" id="treatments"><h2>Treatment approaches</h2><p>Care depends on the individual and the clinical context. These are broad approaches, not a personal treatment plan.</p><TopicLinks entities={related.filter(e => ["treatment", "medication"].includes(e.kind))}/><SafetyNote compact>Treatment decisions should be made with a qualified healthcare professional.</SafetyNote></section></>}
      {entity.kind === "symptom" && <><section className="detail-section" id="conditions"><h2>Commonly associated conditions</h2><p>These conditions may involve this symptom, but many other explanations are possible. This list is not exhaustive.</p><TopicLinks entities={conditions}/></section><section className="detail-section" id="related-symptoms"><h2>Symptoms in connected topics</h2><p>These symptoms appear in some of the same educational condition profiles. They need not occur together.</p><TopicLinks entities={library.entities.filter(e => symptomIds.has(e.id)).slice(0, 12)}/></section><section className="detail-section" id="contributing-factors"><h2>Factors discussed in connected conditions</h2><p>These factors belong to related condition profiles; a connection does not establish the cause of a symptom.</p><TopicLinks entities={library.entities.filter(e => riskIds.has(e.id)).slice(0, 8)}/></section></>}
      {treatment && <><section className="detail-section" id="role"><h2>General role and purpose</h2><p>{entity.details.mechanism || entity.description}</p></section><section className="detail-section" id="conditions"><h2>Conditions it may be used for</h2><p>Suitability depends on professional assessment. Not every approach is appropriate for every person with a condition.</p><TopicLinks entities={conditions}/></section><section className="detail-section" id="safety"><h2>Important safety information</h2><SafetyNote>{entity.details.safety}</SafetyNote><p>This is not a complete list of side effects, contraindications, or interactions. Consult the original patient information and a healthcare professional.</p></section></>}
      {entity.kind === "body-system" && <><section className="detail-section" id="conditions"><h2>Related conditions</h2><TopicLinks entities={conditions}/></section><section className="detail-section" id="symptoms"><h2>Related symptoms</h2><TopicLinks entities={ofKind("symptom")}/>{!ofKind("symptom").length && <p>Explore the connected conditions above for their associated symptoms.</p>}</section></>}
      {entity.kind === "risk-factor" && <><section className="detail-section" id="conditions"><h2>Connected health conditions</h2><p>The relevance and strength of an association depend on the condition and individual context.</p><TopicLinks entities={conditions}/></section><SafetyNote>{entity.details.safety}</SafetyNote></>}
      {system && entity.kind !== "body-system" && <section className="detail-section" id="body-system"><h2>Relevant body system</h2><TopicLinks entities={[system]}/><p>Body systems interact; this primary classification does not exclude effects on other systems.</p></section>}
      {entity.kind === "condition" && conditions.length > 0 && <section className="detail-section" id="related-conditions"><h2>Continue exploring</h2><p>Related topics for comparison or further learning—not interchangeable diagnoses.</p><TopicLinks entities={conditions}/></section>}
      {entity.details.attention && <section className="detail-section" id="medical-attention"><h2>When to seek medical attention</h2><SafetyNote urgent>{entity.details.attention}</SafetyNote></section>}
      <section className="detail-section" id="sources"><h2>Sources & further reading</h2><p>Follow these authoritative references for more detailed and up-to-date information.</p><SourceReferences sources={entity.sources}/></section>
    </div><aside className="detail-aside"><div className="on-this-page"><h3>On this page</h3><a href="#overview">Overview</a>{entity.kind === "condition" && <><a href="#symptoms">Common symptoms</a><a href="#causes">Causes and triggers</a><a href="#risk-factors">Risk factors</a><a href="#diagnosis">Diagnosis overview</a><a href="#treatments">Treatment approaches</a></>}{entity.kind !== "condition" && <a href="#conditions">Associated conditions</a>}{treatment && <a href="#safety">Safety information</a>}{entity.details.attention && <a href="#medical-attention">When to seek care</a>}<a href="#sources">Sources & references</a></div><div className="detail-graph-card"><div className="detail-graph-art"><Network size={46} strokeWidth={1.2}/></div><h3>See how it all connects.</h3><p>Explore {entity.name.toLowerCase()} in the interactive knowledge graph.</p><Link href={`/explore?topic=${id}`} className="button button-primary">Explore connections <ArrowRight size={15}/></Link></div><div className="detail-source-note"><ShieldCheck size={21}/><p><strong>Education, not medical advice.</strong>This summary is a starting point for learning. It does not replace the original references or a clinical assessment.</p></div>{entity.kind === "condition" && <Link href={`/compare?a=${id}`} className="detail-compare-link">Compare with another condition <ArrowRight size={16}/></Link>}</aside></div>
  </article>;
}
